### ISSUE TITLE
Shadow issue

### ISSUE THREAD

**Issue by DjMike238** [kkartaltepe/obs-text-pango#14]
I'm using the latest v1.0 release of the plugin with OBS Studio 26.1.1 (64-bit) on Windows 10, and I'm having a weird issue with shadows. As you can see in the image below, it has a dark outline, for some reason.

![image](https://user-images.githubusercontent.com/22237379/120366734-4b96d000-c310-11eb-9fd9-f53c4755a2be.png)

Judging from the preview in the properties window for the text source, the text itself also has this issue:

![image](https://user-images.githubusercontent.com/22237379/120366898-7ed95f00-c310-11eb-9326-6591e9b3f6a2.png)

Is there any way to fix this?

This is my current config for the source, using a font from file (since for some reason the installed version of the font isn't applied by the plugin, even if font selector shows me that font without any issues) and reading text from a file:

![image](https://user-images.githubusercontent.com/22237379/120367077-b9db9280-c310-11eb-9a2e-f8d4cda179ad.png)

Thanks in advance.

**Comment by kkartaltepe** [comment]
Thanks for the report ill take a look, it looks like we may not be blending alpha correctly.

**Comment by kkartaltepe** [comment]
This should be fixed in 2823034b89982e92b5fc13f47eef444687dcc1f1 though im not sure when Ill be able to make time for a release, maybe sometime next month.

**Comment by DjMike238** [comment]
Hey, any news on the new release? 😅

**Comment by kkartaltepe** [comment]
Sorry there were some issues with build tools when I tried to build for windows last month and its a pain to get a VM going so I havnt created a release yet. Hopefully I have some time to try and get a vm going or something and release it.
