### ISSUE TITLE
Text rendered in a bitmap font

### ISSUE THREAD

**Issue by munzirtaha** [kkartaltepe/obs-text-pango#15]
Hi,
I tested this plugin and I got a bad resolution for the fonts like in this image...

![obs-pango-issue](https://user-images.githubusercontent.com/2936425/122644077-ef0f1f80-d11b-11eb-8ab2-56f12b00b583.png)

**Comment by kkartaltepe** [comment]
This looks correct to me. If you want higher quality increase the font size when selecting the font. The default for freetype is now 256 so try that. Essentially you should use about as many points as you text will be pixels tall. In this example you have text that is probably 500pixels tall, at maybe the default 64pt.

**Comment by munzirtaha** [comment]
Thanks, but look at the properties window itself.

![obs-pango-issue](https://user-images.githubusercontent.com/2936425/122654855-d96b1b80-d156-11eb-9050-aaaeef7cec63.png)

The default settings shows the text pixilated. The normal user won't figure it out easily, so for usability why not you raise it to 256 by default?

**Comment by kkartaltepe** [comment]
I might, but this plugin is considered complete so im not making any changes except for bug fixes as it takes a considerable amount of effort to release for all platforms.
