### ISSUE TITLE
Not showing in OBS - MAC

### ISSUE THREAD

**Issue by rafed1973** [kkartaltepe/obs-text-pango#23]
Installed using brew on a MAC as per instructions and it did not show on OBS
<img width="613" alt="Screen" src="https://user-images.githubusercontent.com/20783927/180406397-8cd95792-f1b3-46c8-8433-7822ab52da5d.png">

**Comment by rafed1973** [comment]
I used brew as per instructions

**Comment by kkartaltepe** [comment]
I believe you found how to install the plugin from the release page https://github.com/kkartaltepe/obs-text-pango/releases/tag/v1.0

I'll try and add some install instructions to the readme in addition to the build instructions. Thanks.
