### ISSUE TITLE
Change emoji font

### ISSUE THREAD

**Issue by Nerzhhh** [kkartaltepe/obs-text-pango#24]
Hi,
I would like to know if it's possible to change the emoji font, I've been trying to put an other font in `obs-studio\data\obs-plugins\text-pango\fonts\emoji` but that doesn't seem to work even by changing the name of the ttf file.
Thanks for your help :)

**Comment by kkartaltepe** [comment]
If you are on linux then setting your system wide default emoji font will work, if you are mac you must follow the same steps as linux for changing fontconfig but modify the plugin local fontconfig in `obs-studio/plugins/libtext-pango/data`.

Usually that means installing the font, then changing https://github.com/kkartaltepe/obs-text-pango/blob/master/data/apple/conf.d/66-noto-color-emoji.conf#L16 to be your preferred font.

Note only CBDT/CBLC are supported by the released versions, the only font commonly distributed in this format is Noto Emoji Color.
