### ISSUE TITLE
Compilation undex Ubuntu 19.04

### ISSUE THREAD

**Issue by viktor-zhuromskyy** [kkartaltepe/obs-text-pango#9]
I am trying to compile the plugin under Ubuntu 19.04, but the cmake fails.

If you can, can you please compile standalone .so and publish it in releases?

**Comment by kkartaltepe** [comment]
dont have 19.04 available. The dependencies dont change much (except probably glib) so I built a binary for 19.10. Hope that is helpful, but i dont intend to maintain these binaries, you are better off buildng it yourself.

https://github.com/kkartaltepe/obs-text-pango/releases/tag/v1.0
